[package]
name = "RustAudioTest"
version = "0.1.0"
edition = "2024"

[dependencies]
rodio = { version = "0.21.1" }
nalgebra = { version = "0.34.1" }
nalgebra-glm = { version = "0.20.0" }
num-traits = { version = "0.2.19" }
hound = { version = "3.5.1" }